import { createClient } from './vendor/supabase.js';
import { blankProfile, normalizeProfile, normalizeDoi, validateProfile, paperFromCrossref, safeLink, rasterHeaderError } from './model.mjs';

const $=s=>document.querySelector(s);
const el=(tag,text='',cls='')=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
const state={client:null,self:null,payload:blankProfile(),revision:0,dirty:false,busy:false,catalog:[],people:[],submissions:[],published:{},signedUrls:new Map(),generation:0};
const statuses={submitted:'待审核',approved:'已批准',rejected:'已退回',superseded:'历史版本'};
function notice(text='',error=false){const n=$('#notice');n.textContent=text;n.classList.toggle('error',error);}
function dirty(){state.dirty=true;$('#save-state').textContent='有未保存的修改';}
function showError(error){const s=String(error?.message||error||'操作失败'),code=String(error?.code||'');let known=s;if(/revision|conflict|stale/i.test(s))known='草稿已在其他窗口更新，请先刷新并核对内容，避免覆盖。';else if(/otp_expired|invalid.*otp|token.*expired/i.test(code+' '+s))known='验证码无效或已过期，请核对最新邮件；也可返回邮箱输入页重新获取。';else if(/over_email_send_rate_limit|rate.limit|too many requests/i.test(code+' '+s))known='验证码发送过于频繁，请稍后重试。';else if(/email_address_not_authorized|not.invited|invited members|access.denied|disabled|permission|not_authorized|unauthorized/i.test(code+' '+s))known='当前邮箱尚未开通权限，或权限已停用，请联系管理员。';else if(/Failed to fetch|NetworkError/i.test(s))known='网络连接未成功，请检查网络后重试。当前页面的修改尚未保存。';notice(known,true);}
async function busy(fn){if(state.busy)return;state.busy=true;const controls=[...document.querySelectorAll('button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled])')];controls.forEach(b=>b.disabled=true);try{return await fn();}catch(e){showError(e);}finally{state.busy=false;controls.filter(b=>b.isConnected).forEach(b=>b.disabled=false);}}
async function rpc(name,args={}){const {data,error}=await state.client.rpc(name,args);if(error)throw error;return data;}
const idFor=()=>`f-${crypto.randomUUID()}`;
function field(parent,label,key,value='',opts={}){const wrap=el('div','','field'),id=idFor(),l=el('label',label);l.htmlFor=id;let input;if(opts.options){input=el('select');for(const [v,txt]of opts.options){const o=el('option',txt);o.value=v;input.append(o);}}else{input=el(opts.long?'textarea':'input');if(!opts.long)input.type=opts.type||'text';input.maxLength=opts.max||((opts.long)?3000:200);if(opts.long)input.rows=opts.rows||3;}input.id=id;input.dataset.field=key;input.value=value??'';if(opts.required)input.required=true;if(opts.min)input.min=opts.min;if(opts.maxValue)input.max=opts.maxValue;if(opts.placeholder)input.placeholder=opts.placeholder;wrap.append(l,input);if(opts.hint)wrap.append(el('p',opts.hint,'hint'));parent.append(wrap);return input;}
function translation(parent,fields){const d=el('details','','translation');d.append(el('summary','英文内容（选填）'));fields(d);parent.append(d);}
function fieldsFrom(card){return Object.fromEntries([...card.querySelectorAll('[data-field]')].map(n=>[n.dataset.field,n.value.trim()]));}
function collect(){const p=blankProfile();Object.assign(p,fieldsFrom($('#basic-fields')));p.avatar_path=state.payload.avatar_path||'';p.projects=[...$('#project-list').children].map(c=>({id:c.dataset.id,...fieldsFrom(c),image_path:c.dataset.imagePath||''}));p.papers=[...$('#paper-list').children].map(c=>{const f=fieldsFrom(c);return {...f,year:Number(f.year)};});p.links=[...$('#link-list').children].map(fieldsFrom);return p;}
function itemCard(parent,title){const card=el('div','','item-card'),top=el('div','','item-top');top.append(el('h3',title));const remove=el('button','移除','danger');remove.type='button';remove.addEventListener('click',()=>{card.remove();dirty();});top.append(remove);card.append(top);parent.append(card);return card;}
async function signedImage(path,img){const generation=state.generation;if(!path){img.hidden=true;img.removeAttribute('src');return;}try{let cached=state.signedUrls.get(path),url=cached?.expires>Date.now()?cached.url:null;if(!url){const {data,error}=await state.client.storage.from('member-drafts').createSignedUrl(path,300);if(error)throw error;if(generation!==state.generation)return;url=data.signedUrl;state.signedUrls.set(path,{url,expires:Date.now()+240000});}if(generation!==state.generation)return;img.src=url;img.hidden=false;}catch{if(generation===state.generation)img.hidden=true;}}
async function upload(file){if(!state.self?.account?.member_id)throw new Error('此账号未绑定个人主页。');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file?.type];if(!ext||file.size>5*1024*1024||file.size===0)throw new Error('请上传不超过5 MB的 JPG、PNG 或 WebP图片。');const headerError=rasterHeaderError(new Uint8Array(await file.arrayBuffer()),file.type);if(headerError)throw new Error(headerError);const bitmap=await createImageBitmap(file);const pixels=bitmap.width*bitmap.height,edge=Math.max(bitmap.width,bitmap.height);bitmap.close();if(pixels>20000000||edge>10000)throw new Error('图片尺寸过大，请缩小到2000万像素以内。');const path=`${state.self.account.member_id}/${crypto.randomUUID()}.${ext}`;const {error}=await state.client.storage.from('member-drafts').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'3600'});if(error)throw error;return path;}
function addProject(p={}){if($('#project-list').children.length>=3)throw new Error('最多展示3项科研项目。');const c=itemCard($('#project-list'),'科研项目');c.dataset.id=p.id||crypto.randomUUID();c.dataset.imagePath=p.image_path||'';field(c,'项目名称','title',p.title,{max:200,required:true});for(const [k,label,hint] of [['question','研究什么问题？','用几句话说明科学问题与意义。'],['approach','怎样研究？','简述思路与方法。'],['contribution','您承担什么工作？','说明本人负责的部分。'],['progress','可公开的进展','可写已发表结果或获准公开的阶段进展。']])field(c,label,k,p[k],{long:true,hint});const image=el('img','','image-preview');image.alt='项目配图预览';image.hidden=true;c.append(image);if(p.image_path)signedImage(p.image_path,image);const l=el('label','项目配图'),file=el('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';l.append(file);c.append(l);file.addEventListener('change',()=>{const f=file.files[0];if(f)busy(async()=>{c.dataset.imagePath=await upload(f);await signedImage(c.dataset.imagePath,image);dirty();notice('图片已上传，请保存草稿。');});});const clear=el('button','移除配图');clear.type='button';clear.addEventListener('click',()=>{c.dataset.imagePath='';image.hidden=true;file.value='';dirty();});c.append(clear);field(c,'图注','image_caption',p.image_caption,{long:true,rows:2});field(c,'图片来源','image_source',p.image_source,{max:500,hint:'例如：本人绘制；或论文 DOI 与图号，并确认可公开使用。'});translation(c,d=>{field(d,'Project title','title_en',p.title_en);for(const [k,label]of [['question','Research question'],['approach','Approach'],['contribution','My contribution'],['progress','Public progress'],['image_caption','Figure caption']])field(d,label,k+'_en',p[k+'_en'],{long:true});});}
function addPaper(p={}){if($('#paper-list').children.length>=30)throw new Error('最多展示30篇论文。');if(p.doi&&collect().papers.some(x=>x.doi.toLowerCase()===p.doi.toLowerCase()))throw new Error('这篇论文已添加。');const c=itemCard($('#paper-list'),'论文');field(c,'DOI','doi',p.doi,{required:true,max:255});field(c,'论文题名','title',p.title,{required:true,max:1000});field(c,'作者（按论文署名顺序）','authors',Array.isArray(p.authors)?p.authors.join('; '):p.authors,{long:true,required:true,max:2000});const grid=el('div','','field-grid');c.append(grid);field(grid,'期刊','journal',p.journal,{required:true,max:200});field(grid,'正式发表年份','year',p.year,{type:'number',min:1900,maxValue:new Date().getFullYear()+1,required:true});field(c,'成果背景','context',p.context||'in_lab',{options:[['in_lab','在本课题组期间'],['before_lab','入组前成果']]});field(c,'本人贡献（选填）','contribution',p.contribution,{long:true,rows:2,hint:'共同第一作者、通讯作者等身份以正式论文为准。'});translation(c,d=>field(d,'My contribution','contribution_en',p.contribution_en,{long:true}));}
function addLink(l={}){if($('#link-list').children.length>=5)throw new Error('最多添加5个学术链接。');const c=itemCard($('#link-list'),'学术链接');field(c,'名称','label',l.label,{max:200,required:true});field(c,'链接地址','url',l.url,{type:'url',max:2048,required:true,placeholder:'https://…'});}
function renderEditor(){const m=state.self.member,p=state.payload;$('#identity-card').replaceChildren();if(m?.image){const img=el('img');img.src='../'+m.image.replace(/^\.\//,'');img.alt=m.name;$('#identity-card').append(img);}const info=el('div');info.append(el('strong',m?.name||'我的主页'),el('p',[m?.role?.zh,m?.affiliation?.zh].filter(Boolean).join(' · ')));$('#identity-card').append(info);const basics=$('#basic-fields');basics.replaceChildren();field(basics,'个人简介','bio',p.bio,{long:true,hint:'建议100–200字，说明研究经历与兴趣。'});field(basics,'研究兴趣','interests',p.interests,{long:true,rows:2});field(basics,'教育经历','education',p.education,{long:true,rows:3});field(basics,'公开联系邮箱','public_email',p.public_email,{type:'email',max:254,hint:'选填；登录邮箱不会自动公开。'});translation(basics,d=>{field(d,'Biography','bio_en',p.bio_en,{long:true});field(d,'Research interests','interests_en',p.interests_en,{long:true});field(d,'Education','education_en',p.education_en,{long:true});});for(const id of ['project-list','paper-list','link-list'])$('#'+id).replaceChildren();p.projects.forEach(addProject);p.papers.forEach(addPaper);p.links.forEach(addLink);signedImage(p.avatar_path,$('#avatar-preview'));state.dirty=false;$('#save-state').textContent=`已保存草稿 · 版本 ${state.revision}`;}
async function saveDraft(){const payload=validateProfile(collect()),saved=await rpc('save_profile',{p_payload:payload,p_expected_revision:state.revision});state.payload=normalizeProfile(saved.payload||payload);state.revision=saved.revision;state.dirty=false;$('#save-state').textContent=`已保存 · ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} · 版本 ${state.revision}`;return saved;}
function showView(view){for(const n of ['editor','review','access'])$('#'+n+'-view').hidden=n!==view;document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
function appendCopy(parent,label,text){if(!text)return;const b=el('div','','preview-block');b.append(el('h3',label),el('p',text,'preview-copy'));parent.append(b);}
function contentPreview(parent,p,member){parent.replaceChildren();if(member?.name)parent.append(el('h2',member.name));for(const [key,label]of [['bio','个人简介'],['interests','研究兴趣'],['education','教育经历']]){appendCopy(parent,label,p[key]);appendCopy(parent,label+'（英文）',p[key+'_en']);}if(p.public_email)appendCopy(parent,'公开邮箱',p.public_email);if(p.avatar_path){const img=el('img','','avatar-preview');img.alt='头像';parent.append(img);signedImage(p.avatar_path,img);}for(const project of p.projects||[]){const b=el('section','','preview-block');b.append(el('h3',project.title||'未命名项目'));if(project.title_en)b.append(el('p',project.title_en+'（英文标题）'));for(const[k,label]of [['question','科学问题'],['approach','研究思路'],['contribution','本人工作'],['progress','公开进展']]){if(project[k])b.append(el('h4',label),el('p',project[k],'preview-copy'));if(project[k+'_en'])b.append(el('h4',label+'（英文）'),el('p',project[k+'_en'],'preview-copy'));}if(project.image_path){const img=el('img');img.alt=project.image_caption||project.title||'项目配图';b.append(img);signedImage(project.image_path,img);if(project.image_caption)b.append(el('p',project.image_caption,'hint'));if(project.image_caption_en)b.append(el('p','英文图注：'+project.image_caption_en,'hint'));b.append(el('p','图片来源：'+(project.image_source||''),'hint'));}parent.append(b);}if(p.papers?.length){const papers=el('section','','preview-block');papers.append(el('h3','发表论文'));for(const paper of p.papers){const b=el('article','','preview-paper');b.append(el('strong',paper.title),el('p',paper.authors),el('p',`${paper.journal} · ${paper.year}${paper.context==='before_lab'?' · 入组前成果':''}`));try{const a=el('a','DOI: '+normalizeDoi(paper.doi));a.href='https://doi.org/'+normalizeDoi(paper.doi);a.target='_blank';a.rel='noopener noreferrer';b.append(a);}catch{}if(paper.contribution)b.append(el('p',paper.contribution));if(paper.contribution_en)b.append(el('p','英文贡献说明：'+paper.contribution_en));papers.append(b);}parent.append(papers);}if(p.links?.length){const links=el('section','','preview-block');links.append(el('h3','学术链接'));for(const l of p.links){if(safeLink(l.url)){const a=el('a',l.label+' ↗');a.href=safeLink(l.url);a.target='_blank';a.rel='noopener noreferrer';const line=el('p');line.append(a);links.append(line);}}parent.append(links);}if(!p.bio&&!p.projects?.length&&!p.papers?.length)parent.append(el('p','还没有补充个人研究内容。','empty-state'));}
async function loadSelf(){const generation=++state.generation;const self=await rpc('portal_self');if(generation!==state.generation)return;state.self=self;state.revision=self.draft?.revision||0;state.payload=normalizeProfile(self.draft?.payload||{});$('#account-label').textContent=self.account.email;$('#account-label').hidden=false;$('#sign-out').hidden=false;$('#login-view').hidden=true;$('#workspace').hidden=false;const isAdmin=self.account.role==='admin',hasProfile=!!self.account.member_id;document.querySelector('[data-view=editor]').hidden=!hasProfile;for(const v of ['review','access'])document.querySelector(`[data-view=${v}]`).hidden=!isAdmin;$('#workspace-title').textContent=isAdmin?'审核与成员管理':self.member?.name+'的个人主页';$('#workspace-eyebrow').textContent=isAdmin?'Tian Lab · 管理员':'Tian Lab · 我的研究主页';$('#workspace-subtitle').textContent=isAdmin?'审核研究内容，管理访问权限。':'编辑并保存草稿，准备好后提交审核。';$('#public-link').hidden=!hasProfile;if(hasProfile){$('#public-link').href='../zh/person-'+self.account.member_id+'.html';renderEditor();const s=$('#member-status');s.replaceChildren(el('h2','审核进度'));const latest=self.latest_submission||self.submission;if(latest){s.append(el('p',statuses[latest.status]||latest.status));if(latest.review_note||latest.note)s.append(el('p',latest.review_note||latest.note));}else s.append(el('p','保存完成后，点击“提交审核”。已公开版本会保留至下一次发布成功。'));}showView(isAdmin?'review':'editor');notice();if(isAdmin)await loadReviews();}
function liveVersion(memberId){return state.published[memberId]?.version;}
async function refreshLive(){const r=await fetch('../data/member-profiles.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('暂时无法读取公开版本。');state.published=(await r.json()).profiles||{};}
async function loadReviews(){const data=await rpc('list_submissions');state.submissions=Array.isArray(data)?data:data.items||[];await refreshLive().catch(()=>{});renderReviews();}
function renderReviews(){const root=$('#review-list');root.replaceChildren();if(!state.submissions.length){root.append(el('p','还没有成员提交内容。','empty-state'));return;}for(const s of state.submissions){const card=el('article','','panel'),top=el('div','','section-top'),heading=el('div');heading.append(el('h3',s.member_name||state.people.find(x=>x.id===s.member_id)?.name||s.member_id));const meta=el('p',new Date(s.created_at).toLocaleString('zh-CN'),'review-meta');meta.append(el('span',statuses[s.status]||s.status,'status-pill '+s.status));heading.append(meta);if(liveVersion(s.member_id)===s.id)heading.append(el('p','此版本正在网站展示','hint'));else if(s.is_published||s.published)heading.append(el('p','后台已选定此版本，尚需核对网站发布结果','hint'));top.append(heading);card.append(top);const d=el('details');d.append(el('summary','查看内容与版本对照'));const diff=el('div','','review-diff'),before=el('div'),after=el('div');before.append(el('h4','当前获批版本'));const existing=state.submissions.find(x=>x.member_id===s.member_id&&(x.is_published||x.published));const beforeBody=el('div');contentPreview(beforeBody,s.published_content||existing?.payload||{},null);before.append(beforeBody);after.append(el('h4','本次提交'));const afterBody=el('div');contentPreview(afterBody,s.payload||{},null);after.append(afterBody);diff.append(before,after);d.append(diff);card.append(d);if(s.review_note||s.note)card.append(el('p','审核意见：'+(s.review_note||s.note),'review-note'));if(s.status==='submitted'){const note=field(card,'审核意见（退回时必填）','review_note','',{long:true,rows:2});const actions=el('div','','review-actions');for(const [decision,label]of [['approve','批准此版本'],['reject','退回修改']]){const b=el('button',label,decision==='approve'?'primary':'');b.type='button';b.addEventListener('click',()=>busy(async()=>{if(decision==='reject'&&!note.value.trim())throw new Error('请填写退回原因，方便成员修改。');await rpc('review_submission',{p_submission_id:s.id,p_decision:decision,p_note:note.value.trim()});await loadReviews();notice(decision==='approve'?'已批准该版本。点击“发布已批准内容”更新网站。':'已退回，成员可根据意见修改后重新提交。');}));actions.append(b);}card.append(actions);}else if(s.status==='approved'&&!(s.is_published||s.published)){const b=el('button','恢复为待发布版本');b.type='button';b.addEventListener('click',()=>busy(async()=>{await rpc('restore_publication',{p_submission_id:s.id});await loadReviews();notice('已选择历史版本，点击发布后更新网站。');}));card.append(b);}root.append(card);}}
async function loadAccess(){const data=await rpc('list_member_access');const entries=Array.isArray(data)?data:data.items||data.access||[];const picker=$('#access-member');picker.replaceChildren();const no=el('option','仅管理后台（无个人主页）');no.value='';picker.append(no);for(const m of state.people){const o=el('option',m.name+' · '+(m.role?.zh||''));o.value=m.id;picker.append(o);}const root=$('#access-list');root.replaceChildren();for(const a of entries.filter(x=>x.email&&x.invited!==false)){const row=el('div','','access-row'),info=el('div');info.append(el('strong',a.email),el('small',`${a.member_name||state.people.find(x=>x.id===a.member_id)?.name||'后台管理'} · ${a.role==='admin'?'管理员':'成员'} · ${a.enabled?'已开通':'已停用'}`));row.append(info);if(a.email!==state.self.account.email){const b=el('button',a.enabled?'停用权限':'重新开通',a.enabled?'danger':'');b.type='button';b.addEventListener('click',()=>busy(async()=>{await rpc('set_member_access',{p_email:a.email,p_member_id:a.member_id,p_role:a.role,p_enabled:!a.enabled});await loadAccess();notice('访问权限已更新。');}));row.append(b);}root.append(row);}}

$('#profile-form').addEventListener('input',dirty);
$('#profile-form').addEventListener('submit',e=>{e.preventDefault();busy(async()=>{await saveDraft();notice('草稿已保存，仅本人及审核管理员可查看。');});});
$('#submit-profile').addEventListener('click',()=>{if(!$('#profile-form').reportValidity())return;busy(async()=>{await saveDraft();const s=await rpc('submit_profile',{p_expected_revision:state.revision});$('#member-status').replaceChildren(el('h2','审核进度'),el('p','已提交审核。您可以继续编辑草稿，已提交的版本保持不变。'));notice('已提交审核，正式网站暂时保持原版。');});});
$('#preview-profile').addEventListener('click',()=>{contentPreview($('#preview-content'),collect(),state.self.member);$('#preview-dialog').showModal();});
$('#close-preview').addEventListener('click',()=>$('#preview-dialog').close());
for(const [id,fn]of [['add-project',()=>addProject()],['add-paper',()=>addPaper()],['add-link',()=>addLink()]])$('#'+id).addEventListener('click',()=>{try{fn();dirty();}catch(e){showError(e);}});
$('#avatar-file').addEventListener('change',()=>{const file=$('#avatar-file').files[0];if(file)busy(async()=>{state.payload.avatar_path=await upload(file);await signedImage(state.payload.avatar_path,$('#avatar-preview'));dirty();notice('头像已上传，请保存草稿。');});});
$('#reset-avatar').addEventListener('click',()=>{state.payload.avatar_path='';$('#avatar-file').value='';$('#avatar-preview').hidden=true;dirty();});
$('#add-catalog-paper').addEventListener('click',()=>{try{const p=state.catalog.find(x=>x.id===$('#catalog-picker').value);if(!p)throw new Error('请先选择一篇论文。');addPaper({...p,context:'in_lab',contribution:''});dirty();notice('已添加，请核对本人署名与成果背景。');}catch(e){showError(e);}});
$('#fetch-doi').addEventListener('click',()=>busy(async()=>{const doi=normalizeDoi($('#doi-import').value),r=await fetch('https://api.crossref.org/works/'+encodeURIComponent(doi),{signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('暂时无法获取这条DOI，可使用“手动添加论文”。');const result=await r.json();addPaper(paperFromCrossref(result.message,doi));dirty();notice('书目信息已填入草稿，请核对作者、年份及本人贡献。');}));
for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>busy(async()=>{const v=b.dataset.view;if(v==='review')await loadReviews();if(v==='access')await loadAccess();showView(v);}));
$('#refresh-reviews').addEventListener('click',()=>busy(loadReviews));
$('#check-live').addEventListener('click',()=>busy(async()=>{await refreshLive();renderReviews();$('#publish-state').textContent='已读取网站当前公开版本，请查看各条记录的展示状态。';}));
$('#publish-site').addEventListener('click',()=>busy(async()=>{const {data,error}=await state.client.functions.invoke('publish-site',{body:{}});if(error)throw new Error('发布任务未能启动，获批内容已保留。请检查后台发布配置或在 GitHub 查看详情。');$('#publish-state').textContent='发布任务已启动，网站将在构建与检查成功后更新。可查看发布进度，再点击“检查线上版本”。';notice('发布请求已接收。');}));
$('#access-role').addEventListener('change',()=>{$('#access-member').required=$('#access-role').value==='member';});
$('#access-form').addEventListener('submit',e=>{e.preventDefault();busy(async()=>{const role=$('#access-role').value,member=$('#access-member').value;if(role==='member'&&!member)throw new Error('成员账号必须选择对应成员。');await rpc('set_member_access',{p_email:$('#access-email').value.trim().toLowerCase(),p_member_id:member||null,p_role:role,p_enabled:true});await loadAccess();$('#access-form').reset();$('#access-member').required=true;notice('权限已开通。请将工作台链接交给成员，使用该邮箱登录。');});});
$('#login-form').addEventListener('submit',e=>{e.preventDefault();busy(async()=>{const email=$('#login-email').value.trim().toLowerCase();const {error}=await state.client.auth.signInWithOtp({email,options:{emailRedirectTo:new URL('./',location.href).href}});if(error)throw error;$('#verify-form').hidden=false;$('#login-form').hidden=true;notice('验证码已请求发送，请检查邮箱。只有受邀邮箱可以访问成员资料。');$('#login-code').focus();});});
$('#verify-form').addEventListener('submit',e=>{e.preventDefault();busy(async()=>{const {error}=await state.client.auth.verifyOtp({email:$('#login-email').value.trim().toLowerCase(),token:$('#login-code').value.trim(),type:'email'});if(error)throw error;await loadSelf();});});
$('#change-email').addEventListener('click',()=>{$('#verify-form').hidden=true;$('#login-form').hidden=false;$('#login-code').value='';notice();});
function clearSessionView(){state.generation++;state.self=null;state.payload=blankProfile();state.revision=0;state.submissions=[];state.published={};state.signedUrls.clear();state.dirty=false;$('#preview-dialog').close();document.querySelectorAll('.avatar-preview,.image-preview,#preview-content img').forEach(img=>{img.removeAttribute('src');img.hidden=true;});$('#workspace').hidden=true;$('#login-view').hidden=false;$('#login-form').hidden=false;$('#verify-form').hidden=true;$('#account-label').hidden=true;$('#account-label').textContent='';$('#sign-out').hidden=true;$('#login-code').value='';for(const id of ['basic-fields','project-list','paper-list','link-list','review-list','access-list','preview-content','identity-card','member-status'])$('#'+id).replaceChildren();}
$('#sign-out').addEventListener('click',()=>busy(async()=>{const {error}=await state.client.auth.signOut({scope:'local'});if(error)throw error;clearSessionView();notice('已退出登录。');}));
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
async function start(){try{const configResponse=await fetch('./config.json',{cache:'no-store'});if(!configResponse.ok)throw new Error('无法读取工作台配置，请稍后再试。');const config=await configResponse.json();$('#login-view').hidden=false;if(!config.enabled||!config.supabaseUrl||!config.supabaseAnonKey){$('#login-form').hidden=true;notice('成员工作台正在接入登录服务，暂未开放。开通后可使用受邀邮箱登录。');return;}const origin=new URL(config.supabaseUrl);if(origin.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(location.hostname))throw new Error('后台连接配置无效。');state.client=createClient(origin.href.replace(/\/$/,''),config.supabaseAnonKey,{auth:{storage:sessionStorage,storageKey:'tianlab-members-session',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});state.client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){clearSessionView();notice('登录已结束，请重新登录。');}});const results=await Promise.all([fetch('../data/publications.json').then(r=>r.json()),fetch('../data/people.json').then(r=>r.json())]);state.catalog=results[0].items;state.people=results[1].items;for(const p of state.catalog){const o=el('option',`${p.year} · ${p.title}`);o.value=p.id;$('#catalog-picker').append(o);}const {data,error}=await state.client.auth.getSession();if(error)throw error;if(data.session)await loadSelf();else notice('使用已开通权限的邮箱登录。');}catch(e){showError(e);}}
start();
